export const UPDATE_GAME_SETTINGS = 'UPDATE_GAME_SETTINGS';
export const SQUARE_CLICKED = 'SQUARE_CLICKED';
export const MINE_CLICKED = 'MINE_CLICKED';
export const MOUSE_CENTER_CLICK = 'MOUSE_CENTER_CLICK';